create table if not exists chat_sessions (
    session_id text primary key,
    customer_identification text references customers(identification),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists chat_messages (
    message_id bigint generated by default as identity primary key,
    session_id text not null references chat_sessions(session_id) on delete cascade,
    role text not null check (role in ('system', 'user', 'assistant', 'tool')),
    content text not null,
    created_at timestamptz not null default now()
);

create index if not exists chat_messages_session_id_idx
    on chat_messages(session_id, created_at);
